from datetime import datetime

from flask_sqlalchemy import SQLAlchemy
from werkzeug.security import check_password_hash, generate_password_hash

db = SQLAlchemy()


class User(db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    password_hash = db.Column(db.String(256), nullable=False)
    role = db.Column(db.String(20), nullable=False, default="student")  # student | teacher
    full_name = db.Column(db.String(150), nullable=False, default="")
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    answers = db.relationship("StudentAnswer", backref="student", lazy=True)

    def set_password(self, password: str):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password: str) -> bool:
        return check_password_hash(self.password_hash, password)


class Topic(db.Model):
    __tablename__ = "topics"

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), nullable=False)
    description = db.Column(db.Text, nullable=False, default="")
    difficulty = db.Column(db.Integer, default=1)  # 1-easy, 2-medium, 3-hard
    created_by = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    questions = db.relationship("Question", backref="topic", lazy=True, cascade="all, delete-orphan")
    creator = db.relationship("User", backref="topics_created")


class Question(db.Model):
    __tablename__ = "questions"

    id = db.Column(db.Integer, primary_key=True)
    topic_id = db.Column(db.Integer, db.ForeignKey("topics.id"), nullable=False)
    text = db.Column(db.Text, nullable=False)
    option_a = db.Column(db.String(300), nullable=False)
    option_b = db.Column(db.String(300), nullable=False)
    option_c = db.Column(db.String(300), nullable=False)
    option_d = db.Column(db.String(300), nullable=False)
    correct_answer = db.Column(db.String(1), nullable=False)  # A|B|C|D
    explanation = db.Column(db.Text, default="")
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    answers = db.relationship("StudentAnswer", backref="question", lazy=True)


class StudentAnswer(db.Model):
    __tablename__ = "student_answers"

    id = db.Column(db.Integer, primary_key=True)
    student_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    question_id = db.Column(db.Integer, db.ForeignKey("questions.id"), nullable=False)
    topic_id = db.Column(db.Integer, db.ForeignKey("topics.id"), nullable=False)
    answer = db.Column(db.String(1), nullable=False)
    is_correct = db.Column(db.Boolean, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)


class AgentReport(db.Model):
    """Reports generated by monitoring / notification agents."""
    __tablename__ = "agent_reports"

    id = db.Column(db.Integer, primary_key=True)
    agent_type = db.Column(db.String(50), nullable=False)  # monitoring | adaptation | notification
    student_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=True)
    message = db.Column(db.Text, nullable=False)
    severity = db.Column(db.String(20), default="info")  # info | warning | danger
    is_read = db.Column(db.Boolean, default=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    student = db.relationship("User", backref="reports")


class AdaptationLog(db.Model):
    """Recommendations produced by the adaptation agent."""
    __tablename__ = "adaptation_logs"

    id = db.Column(db.Integer, primary_key=True)
    student_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    topic_id = db.Column(db.Integer, db.ForeignKey("topics.id"), nullable=True)
    recommendation = db.Column(db.Text, nullable=False)
    ai_generated = db.Column(db.Boolean, default=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    student = db.relationship("User", backref="adaptations")
    topic = db.relationship("Topic", backref="adaptations")


class OrchestratorLog(db.Model):
    """Log of decisions made by the orchestrator agent."""
    __tablename__ = "orchestrator_logs"

    id = db.Column(db.Integer, primary_key=True)
    event_type = db.Column(db.String(50), nullable=False)
    source_agent = db.Column(db.String(50), nullable=False)
    target_agent = db.Column(db.String(50), nullable=True)
    student_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=True)
    payload = db.Column(db.Text, nullable=True)
    decision = db.Column(db.Text, nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    student = db.relationship("User", backref="orchestrator_logs")


class ChatMessage(db.Model):
    """Messages in the AI chat assistant."""
    __tablename__ = "chat_messages"

    id = db.Column(db.Integer, primary_key=True)
    student_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    topic_id = db.Column(db.Integer, db.ForeignKey("topics.id"), nullable=True)
    role = db.Column(db.String(20), nullable=False)  # user | assistant
    content = db.Column(db.Text, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    student = db.relationship("User", backref="chat_messages")
    topic = db.relationship("Topic", backref="chat_messages")


class StudentProfile(db.Model):
    """Trust Score and Self-Regulation Index (SRI) per student."""
    __tablename__ = "student_profiles"

    id = db.Column(db.Integer, primary_key=True)
    student_id = db.Column(db.Integer, db.ForeignKey("users.id"), unique=True, nullable=False)
    trust_score = db.Column(db.Float, default=50.0)   # 0–100, starts at 50
    sri = db.Column(db.Float, default=50.0)            # 0–100 Self-Regulation Index
    updated_at = db.Column(db.DateTime, default=datetime.utcnow)

    student = db.relationship("User", backref=db.backref("profile", uselist=False))

    @property
    def trust_mode(self) -> str:
        """Operational mode derived from Trust Score."""
        if self.trust_score <= 33:
            return "informational"   # все объясняет, ничего без подтверждения
        elif self.trust_score <= 66:
            return "mixed"           # смешанный режим
        else:
            return "autonomous"      # действует сам, уведомляет постфактум

    @property
    def trust_mode_label(self) -> str:
        labels = {
            "informational": "Информационный",
            "mixed": "Смешанный",
            "autonomous": "Автономный",
        }
        return labels.get(self.trust_mode, self.trust_mode)

    @property
    def sri_mode(self) -> str:
        """Intervention level derived from SRI."""
        if self.sri <= 25:
            return "active"     # активный — система максимально вмешивается
        elif self.sri <= 50:
            return "standard"
        elif self.sri <= 75:
            return "passive"
        else:
            return "minimal"    # минимальный — система почти не вмешивается

    @property
    def sri_mode_label(self) -> str:
        labels = {
            "active": "Активный",
            "standard": "Стандартный",
            "passive": "Пассивный",
            "minimal": "Минимальный",
        }
        return labels.get(self.sri_mode, self.sri_mode)


class ConsentProfile(db.Model):
    """Granular per-student consent settings."""
    __tablename__ = "consent_profiles"

    id = db.Column(db.Integer, primary_key=True)
    student_id = db.Column(db.Integer, db.ForeignKey("users.id"), unique=True, nullable=False)
    # Basic level (mandatory, always True)
    academic_data = db.Column(db.Boolean, default=True)
    # Extended level (each item independently opt-in)
    behavioral_analytics = db.Column(db.Boolean, default=False)
    team_data = db.Column(db.Boolean, default=False)
    engagement_index = db.Column(db.Boolean, default=False)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow)

    student = db.relationship("User", backref=db.backref("consent", uselist=False))


class RecommendationInteraction(db.Model):
    """Records how a student responded to an agent recommendation.

    Actions:
      accepted   – followed the recommendation; outcome tracked later
      ignored    – dismissed without acting
      self_verified – resolved on their own without acting on the recommendation
    Trust delta:
      accepted + good outcome → +3
      self_verified           →  0
      ignored                 → −2
    """
    __tablename__ = "recommendation_interactions"

    id = db.Column(db.Integer, primary_key=True)
    student_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    adaptation_log_id = db.Column(db.Integer, db.ForeignKey("adaptation_logs.id"), nullable=False)
    action = db.Column(db.String(20), nullable=False)   # accepted | ignored | self_verified
    outcome_score = db.Column(db.Float, nullable=True)  # score after action (for trust update)
    trust_delta = db.Column(db.Float, default=0.0)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    student = db.relationship("User", backref="recommendation_interactions")
    adaptation_log = db.relationship("AdaptationLog", backref="interactions")


class Project(db.Model):
    """Group project created by a teacher."""
    __tablename__ = "projects"

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), nullable=False)
    description = db.Column(db.Text, default="")
    created_by = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    topic_id = db.Column(db.Integer, db.ForeignKey("topics.id"), nullable=True)
    deadline = db.Column(db.DateTime, nullable=True)
    max_members = db.Column(db.Integer, default=5)
    status = db.Column(db.String(20), default="active")  # active | completed | archived
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    creator = db.relationship("User", backref="projects_created")
    topic = db.relationship("Topic", backref="projects")
    members = db.relationship("ProjectMembership", backref="project", cascade="all, delete-orphan")
    tasks = db.relationship("ProjectTask", backref="project", cascade="all, delete-orphan")


class ProjectMembership(db.Model):
    """Student membership in a group project."""
    __tablename__ = "project_memberships"

    id = db.Column(db.Integer, primary_key=True)
    project_id = db.Column(db.Integer, db.ForeignKey("projects.id"), nullable=False)
    student_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    role = db.Column(db.String(20), default="member")  # member | lead
    joined_at = db.Column(db.DateTime, default=datetime.utcnow)

    student = db.relationship("User", backref="project_memberships")


class ProjectTask(db.Model):
    """Individual task within a group project."""
    __tablename__ = "project_tasks"

    id = db.Column(db.Integer, primary_key=True)
    project_id = db.Column(db.Integer, db.ForeignKey("projects.id"), nullable=False)
    title = db.Column(db.String(200), nullable=False)
    description = db.Column(db.Text, default="")
    assigned_to = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=True)
    status = db.Column(db.String(20), default="pending")  # pending | in_progress | done
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    completed_at = db.Column(db.DateTime, nullable=True)

    assignee = db.relationship("User", backref="assigned_tasks")
